blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from flask_login import login_user, logout_user, login_required, current_user, LoginManager
from werkzeug.security import generate_password_hash, check_password_hash
import re
from services.database import Database
from models.user import User

auth = Blueprint('auth', __name__, url_prefix='/auth',
                 static_folder="static", template_folder="/auth/")
database = Database()


@auth.route("/test")
def auth_test():
    result = database.get_user_by_id("admin")
    print(result)
    user = User(id=result["id"], email=result["email"],
                joined_rooms=result["joined_rooms"], friends=result["friends"])

    login_user(user)

    return current_user.get_all()


@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":

        userDic = {
            "username": request.form.get('username'),
            "password": request.form.get('password'),
            "email": request.form.get('email')
        }
        # Validation of Email address and username
        if not re.match(r"[^@]+@[^@]+\.[^@]+.", userDic["email"]):
            return ('Invalid email address', 400)
        elif not re.match(r"^(?=[a-zA-Z0-9._]{3,20}$)(?!.*[_.]{2})[^_.].*[^_.]$", userDic["username"]):
            return ('Invalid username', 400)

        creation_result = database.create_user(userDic["username"], userDic["email"], generate_password_hash(userDic["password"]))
        print(f"CREATION RESULT: {creation_result}")
        if creation_result:
            print("Creating user")
            newUser = User(id=userDic["username"], email=userDic["email"])
            login = login_user(newUser)
            return redirect(url_for("index"))
        else:
            # TODO Flash message also
            return ('Failed to create', 409)
    else:  # Handling GET
        return render_template("auth/register.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']

        result = database.get_user_by_id(username)

        if result is None:
            flash("Username and/or password is incorrect, try again!",
                  category="error")
            return redirect(url_for("auth.login"))
        
        # Validation of password

        if check_password_hash(result["password"], password):
            user = User(id=result["id"], email=result["email"],
                        joined_rooms=result["joined_rooms"], friends=result["friends"])
            login_user(user)
            return redirect(url_for("index"))
        else:
            flash("Username and/or password is incorrect, try again!",
                  category="error")
            return redirect(url_for("auth.login"))

        return redirect(url_for("index"))
    elif request.method == "GET":
        return render_template("auth/login.html")


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('recon.index'))


def loadHelper(self, user_id):
    return database.get_user_by_id(user_id)

templates/common/menu.html
<aside class="column is-2">
    <nav class="menu">
        <ul class="menu-list">
            <li><a>TRACKS</a></li>
            <li><a>ALBUMS</a></li>
            <li><a>GENRES</a></li>
            <li><a>RECENT</a></li>
        </ul>
    </nav>
</aside>

templates/common/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1>FERRUM</h1>
    </a>

    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        {% if current_user.is_authenticated %}
          <a class=" navbar-item" href ="/workouts">
            🏋️ WORKOUTS
          </a>
          {% endif %}
          
          <div class="buttons">
            
            {% if current_user.is_authenticated %}
            <a class="button is-info" href="/profile">
              {{current_user.get_id()}}
            </a>
            <a class="button is-danger" id = "signout" href={{url_for("auth.logout")}}>
              <strong>SIGN OUT</strong>
            </a>
            {% else %}
            <a class="button is-primary has-tooltip-bottom" disabled>
              Sign in to use features
            </a>
            <a class="button is-primary has-tooltip-bottom" href = {{url_for("auth.register")}}>
              <strong>REGISTER</strong>
            </a>
            <a class="button is-primary has-tooltip-bottom" href = {{url_for("auth.login")}}>
              <strong>SIGN IN</strong>
            </a>
            {% endif %}
    
          </div>
        </div>
    </div>

  </div>
  </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<section class="section">

    {% for category, message in messages %}
    {% if category == "success"%}
    <div class="notification is-primary">
      {% endif %}
      {% if category == "error" %}
      <div class="notification is-danger">
        {% endif %}
      {{message}}
    </div>
    {% endfor %}

</section>

<script>
  $(document).ready(function() {

// Check for click events on the navbar burger icon
$(".navbar-burger").click(function() {

    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
    $(".navbar-burger").toggleClass("is-active");
    $(".navbar-menu").toggleClass("is-active");

});
});
</script>
{% endif %}
{% endwith %}